import Head from "next/head";
import ImportArticle from "../components/ImportArticle";
import Nav from "../components/Nav";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Write New Article | WikiStake </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Nav />

      <ImportArticle/>
    </div>
  );
}
